config/routes.rb
Rails.application.routes.draw do
  resources :articles do
    resources :comments
  end
  get 'home/index'

  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  post '/reactions', to: 'reactions#user_reaction', as: 'user_reaction'
  get '/my_reactions', to: 'reactions#product_with_reactions', as: 'my_reactions' 

  # Defines the root path route ("/")
  root "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
    has_one_attached :photo


    has_many :reactions, dependent: :destroy
    has_many :comment, dependent: :destroy
    has_many :users, through: :comment 


    def count_with_kind(arg)
        number = self.reactions.where(kind: arg).count
        return "#{arg} - #{number}"
    end

    def find_kind_user_relation(user)
        self.reactions.find_by(user_id: user.id).kind 
    end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
  belongs_to :user

  has_many :reactions, dependent: :destroy
end

app/models/reaction.rb
class Reaction < ApplicationRecord
  belongs_to :article, optional: true
  belongs_to :user
  belongs_to :comment, optional: true 


  validates :kind, acceptance: {
    accept: %w[MeGusta NoMeGusta]

  }

  def self.kinds
    %w[MeGusta NoMeGusta]
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :reactions
  has_many :comments
  has_many :articles, through: :reactions 

  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?
  
    protected
  
    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :phone, images_attributes: [:url, :context, :id]])
        devise_parameter_sanitizer.permit(:account_update, keys: [:name, :phone, images_attributes: [:url, :context, :id]])
    end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: %i[ show edit update destroy ]

  # GET /articles or /articles.json
  def index
    @articles = Article.all
  end

  # GET /articles/1 or /articles/1.json
  def show
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles or /articles.json
  def create

    print "\n\n>>>>>>>>>>>>>>\n\n"
    #print params[:article][:photo][:Tempfile]
    print "\n\n"

    #print ActionDispatch::Http::UploadedFile.path()
    #FileUtils.move tmp.path, Rails.root.join("storage")
    print "\n\n params \n\n"

    @article = Article.new(article_params)

    respond_to do |format|
      if @article.save
        if @article.photo.content_type == 'image/jpeg'
          print "Es archivo de foto"
        end 
        format.html { redirect_to article_url(@article), notice: "Article was successfully created." }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1 or /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to article_url(@article), notice: "Article was successfully updated." }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1 or /articles/1.json
  def destroy
    @article.destroy

    respond_to do |format|
      format.html { redirect_to articles_url, notice: "Article was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def article_params
      params.require(:article).permit(:title, :description, :photo)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    before_action :authenticate_user!
    
        def create
            print "\n\n XXXXXXXXXXXXXX\n\n\n"
            print current_user.id
            print "\n\n XXXXXXXXXXXXXX\n\n\n"
            print params[:article_id]
            print "\n\n XXXXXXXXXXXXXX\n\n\n"
            print comment_params[:content]
            print "\n\n XXXXXXXXXXXXXX\n\n\n"

                @article = Article.find(params[:article_id])
                @comment = Comment.new(
                    user_id: current_user.id,
                    article_id: params[:article_id],
                    content: params[:comment][:content]
                  )
                  @comment.save
                #@comment = @article.comment.create(comment_params)
                redirect_to article_path(@article)

        end

      def new

        print  "KKKKKKKKKKKKK"
        print params[:comment][:picture_id]

        @comment = Comment.new(
          user_id: current_user.id,
          picture_id: params[:comment][:picture_id],
          content: params[:comment][:content]
        )
        respond_to do |format|
          if @comment.save!
            format.html { redirect_to picture_path(@comment.picture.id) }
          end
        end
      end
      private
        def comment_params
            params.require(:comment).permit(:content,:article_id )
        end
    
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/reactions_controller.rb
class ReactionsController < ApplicationController
    before_action :authenticate_user!

    def user_reaction
        @user = current_user
        @article = Article.find(params[:article_id])
        reaction = Reaction.find_by(user_id: @user.id, article_id: @article.id)

            if reaction
                return flash.now[:alert] =  "You already reacted to this article" 
            else
                @new_reaction = Reaction.new(user_id: @user.id, article_id: @article.id, kind: params[:kind])
                respond_to do |format|
                    if @new_reaction.save!
                        format.html { redirect_to article_path(@article), notice: "#{current_user.email} has stated tha"   }
                    else
                        format.html { redirect_to article_path(@article), notice: "no paso nada" }
                    end
                end
            end
    end

    def product_with_reactions
        @reactions = current_user.reactions
        article_ids = @reactions.map(&:article_id)
        @articles = Article.where( id: article_ids)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/reactions_helper.rb
module ReactionsHelper
end

app/views/articles/_article.html.erb
<div id="<%= dom_id article %>">
  <p>
    <strong>Title:</strong>
    <%= article.title %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= article.description %>
  </p>

  <p>

    <% if article.photo.attached?  %>
        <%=  image_tag article.photo, size: "340x340"  %>
      <% else %>
        <%=  image_tag 'no_photography.svg', size: "340x340" %>
    <% end %>
  </p>

</div>

app/views/articles/_form.html.erb
<%= form_with(model: article, html: { multipart: true }) do |form| %>
  <% if article.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
        <% article.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_field :description %>
  </div>

    <% if article.photo.attached?  %>
        <%=  image_tag article.photo, size: "340x340"  %>
      <% else %>
        <%=  image_tag 'no_photography.svg', size: "340x340" %>
    <% end %>

  <div>
    <%= form.label :photo, style: "display: block" %>
    <%= form.file_field :photo %>
  </div>

  <div>
    <%= form.submit "Guardar" , class: "btn btn-primary" %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Editing Article</h1>

<%= render "form", article: @article %>

<br>

<div>

  <%= link_to image_tag('back.svg') , :back , class: "btn btn-light", title: "Back to articles" %>
</div>

app/views/articles/index.html.erb
<div class= 'container'>
    <h1>Historias de Gatos</h1>
    <p style="color: green"><%= notice %></p>
    <%= link_to image_tag('addc.svg'), new_article_path %>

    <div class='mt-5 mb-5'>
    <div class='row'>
      <% @articles.each do |article| %>
        <div class='col-4 pyy-2'>
          <div class='card'>
              <div >
                      <%= render article %>
                      <p>
                        <%= link_to image_tag('chat.svg'), article ,  class: "btn btn-light", title: "Coment article " %>
                      </p>
              </div>
          </div>

    </div>
      <% end %>
    </div>
</div>

app/views/articles/new.html.erb
<h1>New article</h1>

<%= render "form", article: @article %>

<br>

<div>
  <%= link_to image_tag('back.svg') , :back , class: "btn btn-light", title: "Back to articles" %>
</div>

app/views/articles/show.html.erb
<p>Show</p>
<p style="color: green"><%= notice %></p>


<%= render @article %>


  <%= render 'reactions/options' %>


<div class='card mt-3 mb-3'style="width: 18rem;" >
  <h5> Comentarios </h5>
  <% @article.comment.each do |coment|%>
      <p>
      <%=  coment.content %>
      </p>
  <% end %>
</div>


<div class='mt-5 mb-5'>
  <div class='card' style="width: 18rem;">
    <h5>Agregar comentario</h5>
    <%= form_with(model: [@article, @article.comment.build], local:true ) do |form| %>
            <p>
              <%= form.label :content  %>
              <%= form.text_area :content %>
            </p>
            <p>
              <%= form.submit 'comentar'  %>
            </p>
    <% end %>
  </div>
</div>

<div class='container mt-1 mb-5'>
  <div class="row row-cols-auto">
      <div class="col">
        <%= link_to image_tag('back.svg'), articles_path, class: "btn btn-light", title: "Back to articles" %>
      </div>

      <div class="col">
        <%= link_to image_tag('edit_note'), edit_article_path(@article) , class: 'btn btn-primary', title: "Edit this article" %>
      </div>

      <div class="col">
        <%= button_to image_tag('delete.svg'), @article, method: :delete , class: 'btn btn-danger', title: "Destroy this article" %>
      </div>

  </div>
</div>

app/views/comments/index.html.erb
hola
<%= print @article.title %>

app/views/home/index.html.erb
<div>
    <%= image_tag 'portada.avif' %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Crazy for Cats</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>


    <!-- Boosttrap -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
    <!-- ========= -->

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>

    <%= render 'shared/navbar' %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <div class='container'>
      <%= yield %>
    </div>

<script src="https://code.jquery.com/jquery-3.6.4.min.js" integrity="sha256-oP6HI9z1XaZNBrJURtCoUT5SUnxFr8s3BzRl+cbzUq8=" crossorigin="anonymous"></script>

<!-- bosttrap -->
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.7/dist/umd/popper.min.js" integrity="sha384-zYPOMqeu1DAVkHiLqWBUTcbYfZ8osu1Nd6Z89ify25QV9guujx43ITvfi12/QExE" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.min.js" integrity="sha384-Y4oOpwW3duJdCWv5ly8SCFYWqFDsfob/3GkgExXKV4idmbt98QcxXYs9UoXAB7BZ" crossorigin="anonymous"></script>
<!-- ========= -->

  </body>
</html>

app/views/reactions/_counters.html.erb
<div class='container'>
    <ul>
        <% Reaction.kinds.each do |kind| %>
            <li>
                <%= @article.reactions.where(kind: kind).count  %> - <%= kind %>
            </li>
        <% end %>
    </ul>
</div>

app/views/reactions/_options.html.erb
<div class='container ms-0' id='reaccion'>

          <div class='row card'>


                <% Reaction.kinds.each do |kind| %>
                    <div class='col-12' id='breacccion'>
                        <%= @article.reactions.where(kind: kind).count  %>
                        <%= button_to image_tag("#{kind}.svg", size: "20x20"), user_reaction_path(article_id: @article.id, kind: kind), title: "#{kind}", method: :post %>   
                    </div>
                <% end %>

                
            </div> 

</div>

app/views/reactions/product_with_reactions.html.erb
<h1> Articulos </h1>

<ul>
    <% @article.each do |article| %>
        <li>
            <%= article.title %> - 
            <%= article.find_kind_user_relation(current_user) %>
            <p>
                <%= link_to "Show this article", article %>
        </li>
    <% end %>
</ul>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-light">
    <div class="container-fluid">
        <%= link_to 'Crazy for Cats', root_path, class: 'navbar-brand' %>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <%= link_to 'Aventuras de Gatos', articles_path, class: 'nav-link' %>
                </li>



            </ul>


            <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                    <% if user_signed_in? %>
                        <% if current_user.name? %>
                            Hola <%= current_user.name %>
                        <% else %>
                            Hola <%= current_user.email %>
                        <% end %>
                    <% else %>
                        Dale registrate o conectate
                    <% end %>
                    </a>
                    <ul class="dropdown-menu">
                        <% if user_signed_in? %>
                            <li><%= button_to 'Cerrar sesión', destroy_user_session_path, class: 'dropdown-item', method: :delete %></li>
                            <li><%= button_to 'Editar usuario', edit_user_registration_path, class: 'dropdown-item', method: :get %></li>
                        <% else %>
                            <li><%= link_to 'Iniciar sesión',  new_user_session_path, class: 'dropdown-item'%></li>
                            <li><hr class="dropdown-divider"></li>
                            <li><%= link_to 'Registro',  new_user_registration_path, class: 'dropdown-item'%></li>
                        <% end %>
                    </ul>
                </li>
            </ul>
        </div>

    </div>
</nav>